databases:
  # PostgreSQL Database
  - name: shifa-alhind-db
    databaseName: shifa
    user: shifa
    plan: free

services:
  # Web Service (Next.js App)
  - type: web
    name: shifa-alhind
    runtime: node
    plan: free
    branch: main
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: shifa-alhind-db
          property: connectionString
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXT_PUBLIC_APP_URL
        sync: false
      - key: NEXT_PUBLIC_APP_NAME
        value: Shifa AlHind
